// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor_data.proto

package sensordata;

public final class SensorDataOuterClass {
  private SensorDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnalogDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensordata.AnalogData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 channelType = 1;</code>
     * @return The channelType.
     */
    int getChannelType();

    /**
     * <code>int32 channelID = 2;</code>
     * @return The channelID.
     */
    int getChannelID();

    /**
     * <code>uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>int32 counter = 4;</code>
     * @return The counter.
     */
    int getCounter();

    /**
     * <code>float data = 5;</code>
     * @return The data.
     */
    float getData();
  }
  /**
   * Protobuf type {@code sensordata.AnalogData}
   */
  public static final class AnalogData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sensordata.AnalogData)
      AnalogDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnalogData.newBuilder() to construct.
    private AnalogData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnalogData() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AnalogData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnalogData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              channelType_ = input.readInt32();
              break;
            }
            case 16: {

              channelID_ = input.readInt32();
              break;
            }
            case 24: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 32: {

              counter_ = input.readInt32();
              break;
            }
            case 45: {

              data_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sensordata.SensorDataOuterClass.internal_static_sensordata_AnalogData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sensordata.SensorDataOuterClass.internal_static_sensordata_AnalogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sensordata.SensorDataOuterClass.AnalogData.class, sensordata.SensorDataOuterClass.AnalogData.Builder.class);
    }

    public static final int CHANNELTYPE_FIELD_NUMBER = 1;
    private int channelType_;
    /**
     * <code>int32 channelType = 1;</code>
     * @return The channelType.
     */
    @java.lang.Override
    public int getChannelType() {
      return channelType_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 2;
    private int channelID_;
    /**
     * <code>int32 channelID = 2;</code>
     * @return The channelID.
     */
    @java.lang.Override
    public int getChannelID() {
      return channelID_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int COUNTER_FIELD_NUMBER = 4;
    private int counter_;
    /**
     * <code>int32 counter = 4;</code>
     * @return The counter.
     */
    @java.lang.Override
    public int getCounter() {
      return counter_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private float data_;
    /**
     * <code>float data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public float getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (channelType_ != 0) {
        output.writeInt32(1, channelType_);
      }
      if (channelID_ != 0) {
        output.writeInt32(2, channelID_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(3, timestamp_);
      }
      if (counter_ != 0) {
        output.writeInt32(4, counter_);
      }
      if (data_ != 0F) {
        output.writeFloat(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (channelType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channelType_);
      }
      if (channelID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channelID_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      if (counter_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, counter_);
      }
      if (data_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sensordata.SensorDataOuterClass.AnalogData)) {
        return super.equals(obj);
      }
      sensordata.SensorDataOuterClass.AnalogData other = (sensordata.SensorDataOuterClass.AnalogData) obj;

      if (getChannelType()
          != other.getChannelType()) return false;
      if (getChannelID()
          != other.getChannelID()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getCounter()
          != other.getCounter()) return false;
      if (java.lang.Float.floatToIntBits(getData())
          != java.lang.Float.floatToIntBits(
              other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANNELTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChannelType();
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelID();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + COUNTER_FIELD_NUMBER;
      hash = (53 * hash) + getCounter();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getData());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.AnalogData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sensordata.SensorDataOuterClass.AnalogData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensordata.AnalogData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensordata.AnalogData)
        sensordata.SensorDataOuterClass.AnalogDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_AnalogData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_AnalogData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sensordata.SensorDataOuterClass.AnalogData.class, sensordata.SensorDataOuterClass.AnalogData.Builder.class);
      }

      // Construct using sensordata.SensorDataOuterClass.AnalogData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channelType_ = 0;

        channelID_ = 0;

        timestamp_ = 0L;

        counter_ = 0;

        data_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_AnalogData_descriptor;
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.AnalogData getDefaultInstanceForType() {
        return sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance();
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.AnalogData build() {
        sensordata.SensorDataOuterClass.AnalogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.AnalogData buildPartial() {
        sensordata.SensorDataOuterClass.AnalogData result = new sensordata.SensorDataOuterClass.AnalogData(this);
        result.channelType_ = channelType_;
        result.channelID_ = channelID_;
        result.timestamp_ = timestamp_;
        result.counter_ = counter_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sensordata.SensorDataOuterClass.AnalogData) {
          return mergeFrom((sensordata.SensorDataOuterClass.AnalogData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sensordata.SensorDataOuterClass.AnalogData other) {
        if (other == sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance()) return this;
        if (other.getChannelType() != 0) {
          setChannelType(other.getChannelType());
        }
        if (other.getChannelID() != 0) {
          setChannelID(other.getChannelID());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getCounter() != 0) {
          setCounter(other.getCounter());
        }
        if (other.getData() != 0F) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sensordata.SensorDataOuterClass.AnalogData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sensordata.SensorDataOuterClass.AnalogData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int channelType_ ;
      /**
       * <code>int32 channelType = 1;</code>
       * @return The channelType.
       */
      @java.lang.Override
      public int getChannelType() {
        return channelType_;
      }
      /**
       * <code>int32 channelType = 1;</code>
       * @param value The channelType to set.
       * @return This builder for chaining.
       */
      public Builder setChannelType(int value) {
        
        channelType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channelType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelType() {
        
        channelType_ = 0;
        onChanged();
        return this;
      }

      private int channelID_ ;
      /**
       * <code>int32 channelID = 2;</code>
       * @return The channelID.
       */
      @java.lang.Override
      public int getChannelID() {
        return channelID_;
      }
      /**
       * <code>int32 channelID = 2;</code>
       * @param value The channelID to set.
       * @return This builder for chaining.
       */
      public Builder setChannelID(int value) {
        
        channelID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channelID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelID() {
        
        channelID_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int counter_ ;
      /**
       * <code>int32 counter = 4;</code>
       * @return The counter.
       */
      @java.lang.Override
      public int getCounter() {
        return counter_;
      }
      /**
       * <code>int32 counter = 4;</code>
       * @param value The counter to set.
       * @return This builder for chaining.
       */
      public Builder setCounter(int value) {
        
        counter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 counter = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCounter() {
        
        counter_ = 0;
        onChanged();
        return this;
      }

      private float data_ ;
      /**
       * <code>float data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public float getData() {
        return data_;
      }
      /**
       * <code>float data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(float value) {
        
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sensordata.AnalogData)
    }

    // @@protoc_insertion_point(class_scope:sensordata.AnalogData)
    private static final sensordata.SensorDataOuterClass.AnalogData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sensordata.SensorDataOuterClass.AnalogData();
    }

    public static sensordata.SensorDataOuterClass.AnalogData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnalogData>
        PARSER = new com.google.protobuf.AbstractParser<AnalogData>() {
      @java.lang.Override
      public AnalogData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnalogData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnalogData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnalogData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sensordata.SensorDataOuterClass.AnalogData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DigitalDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensordata.DigitalData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 channelType = 1;</code>
     * @return The channelType.
     */
    int getChannelType();

    /**
     * <code>int32 cardID = 2;</code>
     * @return The cardID.
     */
    int getCardID();

    /**
     * <code>uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>int32 counter = 4;</code>
     * @return The counter.
     */
    int getCounter();

    /**
     * <code>repeated bool data = 5;</code>
     * @return A list containing the data.
     */
    java.util.List<java.lang.Boolean> getDataList();
    /**
     * <code>repeated bool data = 5;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated bool data = 5;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    boolean getData(int index);
  }
  /**
   * Protobuf type {@code sensordata.DigitalData}
   */
  public static final class DigitalData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sensordata.DigitalData)
      DigitalDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DigitalData.newBuilder() to construct.
    private DigitalData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DigitalData() {
      data_ = emptyBooleanList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DigitalData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DigitalData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              channelType_ = input.readInt32();
              break;
            }
            case 16: {

              cardID_ = input.readInt32();
              break;
            }
            case 24: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 32: {

              counter_ = input.readInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = newBooleanList();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.addBoolean(input.readBool());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                data_ = newBooleanList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sensordata.SensorDataOuterClass.internal_static_sensordata_DigitalData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sensordata.SensorDataOuterClass.internal_static_sensordata_DigitalData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sensordata.SensorDataOuterClass.DigitalData.class, sensordata.SensorDataOuterClass.DigitalData.Builder.class);
    }

    public static final int CHANNELTYPE_FIELD_NUMBER = 1;
    private int channelType_;
    /**
     * <code>int32 channelType = 1;</code>
     * @return The channelType.
     */
    @java.lang.Override
    public int getChannelType() {
      return channelType_;
    }

    public static final int CARDID_FIELD_NUMBER = 2;
    private int cardID_;
    /**
     * <code>int32 cardID = 2;</code>
     * @return The cardID.
     */
    @java.lang.Override
    public int getCardID() {
      return cardID_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int COUNTER_FIELD_NUMBER = 4;
    private int counter_;
    /**
     * <code>int32 counter = 4;</code>
     * @return The counter.
     */
    @java.lang.Override
    public int getCounter() {
      return counter_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.BooleanList data_;
    /**
     * <code>repeated bool data = 5;</code>
     * @return A list containing the data.
     */
    @java.lang.Override
    public java.util.List<java.lang.Boolean>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated bool data = 5;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated bool data = 5;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public boolean getData(int index) {
      return data_.getBoolean(index);
    }
    private int dataMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (channelType_ != 0) {
        output.writeInt32(1, channelType_);
      }
      if (cardID_ != 0) {
        output.writeInt32(2, cardID_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(3, timestamp_);
      }
      if (counter_ != 0) {
        output.writeInt32(4, counter_);
      }
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeBoolNoTag(data_.getBoolean(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (channelType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channelType_);
      }
      if (cardID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cardID_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      if (counter_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, counter_);
      }
      {
        int dataSize = 0;
        dataSize = 1 * getDataList().size();
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sensordata.SensorDataOuterClass.DigitalData)) {
        return super.equals(obj);
      }
      sensordata.SensorDataOuterClass.DigitalData other = (sensordata.SensorDataOuterClass.DigitalData) obj;

      if (getChannelType()
          != other.getChannelType()) return false;
      if (getCardID()
          != other.getCardID()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getCounter()
          != other.getCounter()) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANNELTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChannelType();
      hash = (37 * hash) + CARDID_FIELD_NUMBER;
      hash = (53 * hash) + getCardID();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + COUNTER_FIELD_NUMBER;
      hash = (53 * hash) + getCounter();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.DigitalData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sensordata.SensorDataOuterClass.DigitalData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensordata.DigitalData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensordata.DigitalData)
        sensordata.SensorDataOuterClass.DigitalDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_DigitalData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_DigitalData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sensordata.SensorDataOuterClass.DigitalData.class, sensordata.SensorDataOuterClass.DigitalData.Builder.class);
      }

      // Construct using sensordata.SensorDataOuterClass.DigitalData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channelType_ = 0;

        cardID_ = 0;

        timestamp_ = 0L;

        counter_ = 0;

        data_ = emptyBooleanList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_DigitalData_descriptor;
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.DigitalData getDefaultInstanceForType() {
        return sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance();
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.DigitalData build() {
        sensordata.SensorDataOuterClass.DigitalData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.DigitalData buildPartial() {
        sensordata.SensorDataOuterClass.DigitalData result = new sensordata.SensorDataOuterClass.DigitalData(this);
        int from_bitField0_ = bitField0_;
        result.channelType_ = channelType_;
        result.cardID_ = cardID_;
        result.timestamp_ = timestamp_;
        result.counter_ = counter_;
        if (((bitField0_ & 0x00000001) != 0)) {
          data_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sensordata.SensorDataOuterClass.DigitalData) {
          return mergeFrom((sensordata.SensorDataOuterClass.DigitalData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sensordata.SensorDataOuterClass.DigitalData other) {
        if (other == sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance()) return this;
        if (other.getChannelType() != 0) {
          setChannelType(other.getChannelType());
        }
        if (other.getCardID() != 0) {
          setCardID(other.getCardID());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getCounter() != 0) {
          setCounter(other.getCounter());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sensordata.SensorDataOuterClass.DigitalData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sensordata.SensorDataOuterClass.DigitalData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int channelType_ ;
      /**
       * <code>int32 channelType = 1;</code>
       * @return The channelType.
       */
      @java.lang.Override
      public int getChannelType() {
        return channelType_;
      }
      /**
       * <code>int32 channelType = 1;</code>
       * @param value The channelType to set.
       * @return This builder for chaining.
       */
      public Builder setChannelType(int value) {
        
        channelType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channelType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelType() {
        
        channelType_ = 0;
        onChanged();
        return this;
      }

      private int cardID_ ;
      /**
       * <code>int32 cardID = 2;</code>
       * @return The cardID.
       */
      @java.lang.Override
      public int getCardID() {
        return cardID_;
      }
      /**
       * <code>int32 cardID = 2;</code>
       * @param value The cardID to set.
       * @return This builder for chaining.
       */
      public Builder setCardID(int value) {
        
        cardID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cardID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardID() {
        
        cardID_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int counter_ ;
      /**
       * <code>int32 counter = 4;</code>
       * @return The counter.
       */
      @java.lang.Override
      public int getCounter() {
        return counter_;
      }
      /**
       * <code>int32 counter = 4;</code>
       * @param value The counter to set.
       * @return This builder for chaining.
       */
      public Builder setCounter(int value) {
        
        counter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 counter = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCounter() {
        
        counter_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.BooleanList data_ = emptyBooleanList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = mutableCopy(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bool data = 5;</code>
       * @return A list containing the data.
       */
      public java.util.List<java.lang.Boolean>
          getDataList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(data_) : data_;
      }
      /**
       * <code>repeated bool data = 5;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated bool data = 5;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public boolean getData(int index) {
        return data_.getBoolean(index);
      }
      /**
       * <code>repeated bool data = 5;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, boolean value) {
        ensureDataIsMutable();
        data_.setBoolean(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool data = 5;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(boolean value) {
        ensureDataIsMutable();
        data_.addBoolean(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool data = 5;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = emptyBooleanList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sensordata.DigitalData)
    }

    // @@protoc_insertion_point(class_scope:sensordata.DigitalData)
    private static final sensordata.SensorDataOuterClass.DigitalData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sensordata.SensorDataOuterClass.DigitalData();
    }

    public static sensordata.SensorDataOuterClass.DigitalData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DigitalData>
        PARSER = new com.google.protobuf.AbstractParser<DigitalData>() {
      @java.lang.Override
      public DigitalData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DigitalData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DigitalData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DigitalData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sensordata.SensorDataOuterClass.DigitalData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SensorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensordata.SensorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.sensordata.AnalogData analog = 1;</code>
     * @return Whether the analog field is set.
     */
    boolean hasAnalog();
    /**
     * <code>.sensordata.AnalogData analog = 1;</code>
     * @return The analog.
     */
    sensordata.SensorDataOuterClass.AnalogData getAnalog();
    /**
     * <code>.sensordata.AnalogData analog = 1;</code>
     */
    sensordata.SensorDataOuterClass.AnalogDataOrBuilder getAnalogOrBuilder();

    /**
     * <code>.sensordata.DigitalData digital = 2;</code>
     * @return Whether the digital field is set.
     */
    boolean hasDigital();
    /**
     * <code>.sensordata.DigitalData digital = 2;</code>
     * @return The digital.
     */
    sensordata.SensorDataOuterClass.DigitalData getDigital();
    /**
     * <code>.sensordata.DigitalData digital = 2;</code>
     */
    sensordata.SensorDataOuterClass.DigitalDataOrBuilder getDigitalOrBuilder();

    public sensordata.SensorDataOuterClass.SensorData.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code sensordata.SensorData}
   */
  public static final class SensorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sensordata.SensorData)
      SensorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorData.newBuilder() to construct.
    private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorData() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SensorData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sensordata.SensorDataOuterClass.AnalogData.Builder subBuilder = null;
              if (payloadCase_ == 1) {
                subBuilder = ((sensordata.SensorDataOuterClass.AnalogData) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(sensordata.SensorDataOuterClass.AnalogData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((sensordata.SensorDataOuterClass.AnalogData) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 1;
              break;
            }
            case 18: {
              sensordata.SensorDataOuterClass.DigitalData.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((sensordata.SensorDataOuterClass.DigitalData) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(sensordata.SensorDataOuterClass.DigitalData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((sensordata.SensorDataOuterClass.DigitalData) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sensordata.SensorDataOuterClass.internal_static_sensordata_SensorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sensordata.SensorDataOuterClass.internal_static_sensordata_SensorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sensordata.SensorDataOuterClass.SensorData.class, sensordata.SensorDataOuterClass.SensorData.Builder.class);
    }

    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ANALOG(1),
      DIGITAL(2),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return ANALOG;
          case 2: return DIGITAL;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int ANALOG_FIELD_NUMBER = 1;
    /**
     * <code>.sensordata.AnalogData analog = 1;</code>
     * @return Whether the analog field is set.
     */
    @java.lang.Override
    public boolean hasAnalog() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.sensordata.AnalogData analog = 1;</code>
     * @return The analog.
     */
    @java.lang.Override
    public sensordata.SensorDataOuterClass.AnalogData getAnalog() {
      if (payloadCase_ == 1) {
         return (sensordata.SensorDataOuterClass.AnalogData) payload_;
      }
      return sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance();
    }
    /**
     * <code>.sensordata.AnalogData analog = 1;</code>
     */
    @java.lang.Override
    public sensordata.SensorDataOuterClass.AnalogDataOrBuilder getAnalogOrBuilder() {
      if (payloadCase_ == 1) {
         return (sensordata.SensorDataOuterClass.AnalogData) payload_;
      }
      return sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance();
    }

    public static final int DIGITAL_FIELD_NUMBER = 2;
    /**
     * <code>.sensordata.DigitalData digital = 2;</code>
     * @return Whether the digital field is set.
     */
    @java.lang.Override
    public boolean hasDigital() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.sensordata.DigitalData digital = 2;</code>
     * @return The digital.
     */
    @java.lang.Override
    public sensordata.SensorDataOuterClass.DigitalData getDigital() {
      if (payloadCase_ == 2) {
         return (sensordata.SensorDataOuterClass.DigitalData) payload_;
      }
      return sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance();
    }
    /**
     * <code>.sensordata.DigitalData digital = 2;</code>
     */
    @java.lang.Override
    public sensordata.SensorDataOuterClass.DigitalDataOrBuilder getDigitalOrBuilder() {
      if (payloadCase_ == 2) {
         return (sensordata.SensorDataOuterClass.DigitalData) payload_;
      }
      return sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (sensordata.SensorDataOuterClass.AnalogData) payload_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (sensordata.SensorDataOuterClass.DigitalData) payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (sensordata.SensorDataOuterClass.AnalogData) payload_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (sensordata.SensorDataOuterClass.DigitalData) payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sensordata.SensorDataOuterClass.SensorData)) {
        return super.equals(obj);
      }
      sensordata.SensorDataOuterClass.SensorData other = (sensordata.SensorDataOuterClass.SensorData) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getAnalog()
              .equals(other.getAnalog())) return false;
          break;
        case 2:
          if (!getDigital()
              .equals(other.getDigital())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + ANALOG_FIELD_NUMBER;
          hash = (53 * hash) + getAnalog().hashCode();
          break;
        case 2:
          hash = (37 * hash) + DIGITAL_FIELD_NUMBER;
          hash = (53 * hash) + getDigital().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensordata.SensorDataOuterClass.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sensordata.SensorDataOuterClass.SensorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensordata.SensorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensordata.SensorData)
        sensordata.SensorDataOuterClass.SensorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_SensorData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_SensorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sensordata.SensorDataOuterClass.SensorData.class, sensordata.SensorDataOuterClass.SensorData.Builder.class);
      }

      // Construct using sensordata.SensorDataOuterClass.SensorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sensordata.SensorDataOuterClass.internal_static_sensordata_SensorData_descriptor;
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.SensorData getDefaultInstanceForType() {
        return sensordata.SensorDataOuterClass.SensorData.getDefaultInstance();
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.SensorData build() {
        sensordata.SensorDataOuterClass.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sensordata.SensorDataOuterClass.SensorData buildPartial() {
        sensordata.SensorDataOuterClass.SensorData result = new sensordata.SensorDataOuterClass.SensorData(this);
        if (payloadCase_ == 1) {
          if (analogBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = analogBuilder_.build();
          }
        }
        if (payloadCase_ == 2) {
          if (digitalBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = digitalBuilder_.build();
          }
        }
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sensordata.SensorDataOuterClass.SensorData) {
          return mergeFrom((sensordata.SensorDataOuterClass.SensorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sensordata.SensorDataOuterClass.SensorData other) {
        if (other == sensordata.SensorDataOuterClass.SensorData.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case ANALOG: {
            mergeAnalog(other.getAnalog());
            break;
          }
          case DIGITAL: {
            mergeDigital(other.getDigital());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sensordata.SensorDataOuterClass.SensorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sensordata.SensorDataOuterClass.SensorData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          sensordata.SensorDataOuterClass.AnalogData, sensordata.SensorDataOuterClass.AnalogData.Builder, sensordata.SensorDataOuterClass.AnalogDataOrBuilder> analogBuilder_;
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       * @return Whether the analog field is set.
       */
      @java.lang.Override
      public boolean hasAnalog() {
        return payloadCase_ == 1;
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       * @return The analog.
       */
      @java.lang.Override
      public sensordata.SensorDataOuterClass.AnalogData getAnalog() {
        if (analogBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (sensordata.SensorDataOuterClass.AnalogData) payload_;
          }
          return sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return analogBuilder_.getMessage();
          }
          return sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance();
        }
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       */
      public Builder setAnalog(sensordata.SensorDataOuterClass.AnalogData value) {
        if (analogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          analogBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       */
      public Builder setAnalog(
          sensordata.SensorDataOuterClass.AnalogData.Builder builderForValue) {
        if (analogBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          analogBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       */
      public Builder mergeAnalog(sensordata.SensorDataOuterClass.AnalogData value) {
        if (analogBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance()) {
            payload_ = sensordata.SensorDataOuterClass.AnalogData.newBuilder((sensordata.SensorDataOuterClass.AnalogData) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            analogBuilder_.mergeFrom(value);
          }
          analogBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       */
      public Builder clearAnalog() {
        if (analogBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          analogBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       */
      public sensordata.SensorDataOuterClass.AnalogData.Builder getAnalogBuilder() {
        return getAnalogFieldBuilder().getBuilder();
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       */
      @java.lang.Override
      public sensordata.SensorDataOuterClass.AnalogDataOrBuilder getAnalogOrBuilder() {
        if ((payloadCase_ == 1) && (analogBuilder_ != null)) {
          return analogBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (sensordata.SensorDataOuterClass.AnalogData) payload_;
          }
          return sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance();
        }
      }
      /**
       * <code>.sensordata.AnalogData analog = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sensordata.SensorDataOuterClass.AnalogData, sensordata.SensorDataOuterClass.AnalogData.Builder, sensordata.SensorDataOuterClass.AnalogDataOrBuilder> 
          getAnalogFieldBuilder() {
        if (analogBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = sensordata.SensorDataOuterClass.AnalogData.getDefaultInstance();
          }
          analogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sensordata.SensorDataOuterClass.AnalogData, sensordata.SensorDataOuterClass.AnalogData.Builder, sensordata.SensorDataOuterClass.AnalogDataOrBuilder>(
                  (sensordata.SensorDataOuterClass.AnalogData) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();;
        return analogBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          sensordata.SensorDataOuterClass.DigitalData, sensordata.SensorDataOuterClass.DigitalData.Builder, sensordata.SensorDataOuterClass.DigitalDataOrBuilder> digitalBuilder_;
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       * @return Whether the digital field is set.
       */
      @java.lang.Override
      public boolean hasDigital() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       * @return The digital.
       */
      @java.lang.Override
      public sensordata.SensorDataOuterClass.DigitalData getDigital() {
        if (digitalBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (sensordata.SensorDataOuterClass.DigitalData) payload_;
          }
          return sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return digitalBuilder_.getMessage();
          }
          return sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance();
        }
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       */
      public Builder setDigital(sensordata.SensorDataOuterClass.DigitalData value) {
        if (digitalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          digitalBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       */
      public Builder setDigital(
          sensordata.SensorDataOuterClass.DigitalData.Builder builderForValue) {
        if (digitalBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          digitalBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       */
      public Builder mergeDigital(sensordata.SensorDataOuterClass.DigitalData value) {
        if (digitalBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance()) {
            payload_ = sensordata.SensorDataOuterClass.DigitalData.newBuilder((sensordata.SensorDataOuterClass.DigitalData) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            digitalBuilder_.mergeFrom(value);
          }
          digitalBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       */
      public Builder clearDigital() {
        if (digitalBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          digitalBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       */
      public sensordata.SensorDataOuterClass.DigitalData.Builder getDigitalBuilder() {
        return getDigitalFieldBuilder().getBuilder();
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       */
      @java.lang.Override
      public sensordata.SensorDataOuterClass.DigitalDataOrBuilder getDigitalOrBuilder() {
        if ((payloadCase_ == 2) && (digitalBuilder_ != null)) {
          return digitalBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (sensordata.SensorDataOuterClass.DigitalData) payload_;
          }
          return sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance();
        }
      }
      /**
       * <code>.sensordata.DigitalData digital = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sensordata.SensorDataOuterClass.DigitalData, sensordata.SensorDataOuterClass.DigitalData.Builder, sensordata.SensorDataOuterClass.DigitalDataOrBuilder> 
          getDigitalFieldBuilder() {
        if (digitalBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = sensordata.SensorDataOuterClass.DigitalData.getDefaultInstance();
          }
          digitalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sensordata.SensorDataOuterClass.DigitalData, sensordata.SensorDataOuterClass.DigitalData.Builder, sensordata.SensorDataOuterClass.DigitalDataOrBuilder>(
                  (sensordata.SensorDataOuterClass.DigitalData) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();;
        return digitalBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sensordata.SensorData)
    }

    // @@protoc_insertion_point(class_scope:sensordata.SensorData)
    private static final sensordata.SensorDataOuterClass.SensorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sensordata.SensorDataOuterClass.SensorData();
    }

    public static sensordata.SensorDataOuterClass.SensorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorData>
        PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
      @java.lang.Override
      public SensorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sensordata.SensorDataOuterClass.SensorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensordata_AnalogData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensordata_AnalogData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensordata_DigitalData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensordata_DigitalData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensordata_SensorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensordata_SensorData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021sensor_data.proto\022\nsensordata\"f\n\nAnalo" +
      "gData\022\023\n\013channelType\030\001 \001(\005\022\021\n\tchannelID\030" +
      "\002 \001(\005\022\021\n\ttimestamp\030\003 \001(\004\022\017\n\007counter\030\004 \001(" +
      "\005\022\014\n\004data\030\005 \001(\002\"d\n\013DigitalData\022\023\n\013channe" +
      "lType\030\001 \001(\005\022\016\n\006cardID\030\002 \001(\005\022\021\n\ttimestamp" +
      "\030\003 \001(\004\022\017\n\007counter\030\004 \001(\005\022\014\n\004data\030\005 \003(\010\"m\n" +
      "\nSensorData\022(\n\006analog\030\001 \001(\0132\026.sensordata" +
      ".AnalogDataH\000\022*\n\007digital\030\002 \001(\0132\027.sensord" +
      "ata.DigitalDataH\000B\t\n\007payloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sensordata_AnalogData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensordata_AnalogData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensordata_AnalogData_descriptor,
        new java.lang.String[] { "ChannelType", "ChannelID", "Timestamp", "Counter", "Data", });
    internal_static_sensordata_DigitalData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sensordata_DigitalData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensordata_DigitalData_descriptor,
        new java.lang.String[] { "ChannelType", "CardID", "Timestamp", "Counter", "Data", });
    internal_static_sensordata_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sensordata_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensordata_SensorData_descriptor,
        new java.lang.String[] { "Analog", "Digital", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
